### PR TITLE
[Fix #152]  Sanitize should only remove whitespace at the end of a command

### LINKED ISSUE #152: inf-clojure--make-single-line removes consecutive spaces in strings.
https://github.com/clojure-emacs/inf-clojure/blob/master/inf-clojure.el#L321

```(count "1   5") => 3 ;; Should be 5.```

EDIT: There are 3 spaces between 1 and 5 above. Apparently, this markdown is also removing the consecutive spaces.

### PR DESCRIPTION
**Pull request by arichiardi**
This patch makes sure that we trim at the right of the sanitized command only.

I am open to get rid completely of the sanitation but I do not have the time
now for trying on all the platform.

-----------------

Before submitting the PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [X] The commits are consistent with our [contribution guidelines][1]
- [X] The new code is not generating bytecode or `M-x checkdoc` warnings
- [] You've updated the changelog (if adding/changing user-visible functionality)
- [] You've updated the readme (if adding/changing user-visible functionality)

### CODE REVIEW

**Comment by dotemacs** [comment]
> I do not have the time now for trying on all the platform.

In order to help, I've tested:

```clojure
(count "1   5")
```
on

- ClojureCLR 1.9.0
- Clojure 1.7.0
- Clojure 1.8.0
- Clojure 1.9.0
- Clojure 1.10.0
- Lumo 1.7.0
- Planck 2.10.0

They all return **5** as you'd expect.

**Comment by bbatsov** [comment]
And multi-line evaluations don't mess up the REPL prompt? I recall this conversation was added to avoid having to deal with subprompts that appeared when entering multi-line expressions.

**Comment by arichiardi** [comment]
Thanks for testing! There is also a test 😀

**Comment by dotemacs** [comment]
> And multi-line evaluations don't mess up the REPL prompt? I recall this conversation was added to avoid having to deal with subprompts that appeared when entering multi-line expressions.

This is how it looks for Clojure 1.(7|8|9|10).0 & ClojureCLR 1.9.0:

```
eg.core=> (println 
"foo")
     #_=> foo
nil
eg.core=> 
```

Where I enter <kbd>C-q C-j</kbd> after `println`, followed by RET at the end of the s-expression.

Tried it out with Lumo & Planck and they behaved OK, but only once(!) the `inf-clojure-repl-type` was specified prior to the invocation of their REPLs, via .dir-locals.el:

```emacs-lisp
((nil . ((inf-clojure-lein-cmd . "lumo -r")
         (inf-clojure-minor-mode . t)
         (inf-clojure-repl-type . lumo))))
```

For me, I only need to use this mode for `ClojureCLR`. For the Clojure on JVM I use CIDER. 
I don't really use Planck & I've got some scripts in Lumo, but don't do it on daily basis.
I'd much rather that somebody who is "knee deep" in them check how their REPLs behave for them.

For Joker, I don't use it at all. Even with the above .dir-locals.el modified for Joker's settings, it was still trying to invoke JVM related documentation and throw errors. But once I disabled `eldoc-mode`, the REPL behaved just fine. Still, I'd like somebody who is into Joker with this mode to bless this before you merge the change.

**Comment by arichiardi** [comment]
I am trying that `(count...)` thing working with `lumo` but this is what I see with this patch:

```

cljs.user=> ("count" "counted?")
cljs.user=> cljs.user=>        #_=>          #_=>                                        #_=>   ("count" "counted?")
cljs.user=> cljs.user=>          #_=>                                        #_=>   cljs.user=>        #_=>          #_=>                                        #_=>   ("test")
cljs.user=> (count "test  ")
6
cljs.user=>          #_=>                                        #_=>   ("count" "counted?")
cljs.user=> cljs.user=> (count "11111")
```

It seems like each and every `\n` is generating a subprompt. Probably it is a side-effect and can be treated in some of the post-filter functions that `comint` provides. It definitely rings a bell. I saw this problem already.

**Comment by bbatsov** [comment]
Yeah, that's exactly the problem I tried to solve originally by just converting every expression to a single-line form. Probably some post-filter is going to be a better approach, though. I guess it's a common problem with most REPLs/shells. The visual artefacts weren't the real problem - this actually messes up tooling evals as well.

**Comment by arichiardi** [comment]
It does, and in `lumo`'s case it actually crashes the REPL.

**Pull request merged**
