### PR TITLE
Fix repl type sync

### PR DESCRIPTION
**Pull request by arichiardi**
I opened this PR basically to raise a flag around synchronicity and asking for what is the best way to solve them. It is a very sporadic problem I get when I try to detect the REPL type while waiting for a REPL detection that finishes. As you can imagine these things are difficult to reproduce and I'd like to ask folks to try `inf-clojure` without this patch in `lumo` and report what happens.

I found http://blog.jorgenschaefer.de/2014/05/race-conditions-in-emacs-process-filter.html and put a lock in there, which is a hack.

- [x] The commits are consistent with our [contribution guidelines][1]
- [x] The new code is not generating bytecode or `M-x checkdoc` warnings

Thanks!

[1]: https://github.com/clojure-emacs/inf-clojure/blob/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by arichiardi** [comment]
The PR includes the revert only for convenience. Once you revert on master I'll rebase.

**Comment by arichiardi** [comment]
I have to say that without this is everything looks broken for `lumo` :smile:

**Comment by bbatsov** [comment]
You'll have to rebase.

**Comment by arichiardi** [comment]
Ok restricted the scope of this PR

**Pull request merged**
