### PR TITLE
[WIP] Display evaluation results inline

### PR DESCRIPTION
**Pull request by vharmain**
This PR is an attempt to introduce functionality to display evaluation results inline similarly to [Cider](https://github.com/clojure-emacs/cider). Screenshot below illustrates the goal.

image 

**This PR is a Work-In-Progress**

- [x] Add wrapper functions for displaying the overlay when executing `inf-clojure-eval-last-sexp` or `inf-clojure-eval-last-defun`
- [ ] Get evaluation results from subprocess and display the results in the overlay
- [ ] Decide whether to show overlay by default when calling `inf-clojure-last-sexp` or `inf-clojure-eval-last-defun`

Original code copied from https://github.com/xiongtx/eros/blob/master/eros.el

### CODE REVIEW

**Comment by arichiardi** [comment]
I will have a look at this and maybe create a new branch with added commits to it. Seems super nice!

**Comment by bbatsov** [comment]
I'm closing this PR due to no recent activity. Feel free to re-open it if you ever come back to it.

**Comment by jakub-stastny** [comment]
@vharmain @arichiardi hey guys I have high interest in this feature and I want to get started on this soon (whenever I have time). Let me know if any of you is still interested in this work.

**Comment by vharmain** [comment]
@jakub-stastny nice to hear that you're interested in this! I saw you writing about socket-repl / prepl in Clojurians Slack and it sounds interesting. It would still be cool to have this in inf-clojure even though I'm using nrepl almost exclusively nowadays. It's on my radar to dive deeper into different REPLs and workflows one day.

This was my first stab at emacs lisp and probably because of that I never finished. If I remember right I got the UI side working but the plumbing was missing to get the actual eval results from _somewhere_.

I'm quite busy with work for the next couple of months so I can't promise that I can contribute much but I'm happy to hang around at least. :) I will have more time to invest In the summer if still needed.

**Pull request closed without merging**
