### PR TITLE
Skip empty prompts.

### PR DESCRIPTION
**Pull request by dop**
**Replace this placeholder text with a summary of the changes in your PR.
The more detailed you are, the better.**

-----------------

Before submitting the PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [ ] The commits are consistent with our [contribution guidelines][1]
- [ ] The new code is not generating bytecode or `M-x checkdoc` warnings
- [ ] You've updated the changelog (if adding/changing user-visible functionality)
- [ ] You've updated the readme (if adding/changing user-visible functionality)

Thanks!

[1]: https://github.com/clojure-emacs/inf-clojure/blob/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by dpsutton** [comment]
@dop thanks for the PR!

I think I'm following the code easily enough. But do you think you could add a PR description? It would be nice if we knew where the prompts are coming from. Is this useful mostly when running a subprocess? Or when connected on a socket-repl? 

Can you add some tests? And also we'll want to include this nice functionality in the changelog.

**Comment by dop** [comment]
Oh my, I did not intend to open a PR. Sorry for the noise. I'll let you know if I actually understand the issue.

**Comment by dpsutton** [comment]
@dop well I'm glad you're thinking about the issue. Feel free to discuss here if you want to brainstorm on it.

**Comment by dop** [comment]
@dpsutton I did some investigation and came up with this solution:

```diff
@@ -1293,7 +1286,7 @@ defun inf-clojure--process-response
 will end at (point-max) in the results buffer.  It cuts out the
 output from and including the `inf-clojure-prompt`."
   (let ((redirect-buffer-name inf-clojure--redirect-buffer-name)
-        (sanitized-command (inf-clojure--sanitize-command command)))
+        (sanitized-command (string-trim command)))
     (when (not (string-empty-p sanitized-command))
       (inf-clojure--log-string command "----CMD->")
       (with-current-buffer (inf-clojure--get-redirect-buffer)
```

Why?

`inf-clojure--sanitize-command` appends newline to the command, but so does comint, effectively doing this:

```
$ echo -n "(inc 1)\n\n" | clojure
Clojure 1.11.1
user=> 2
user=> user=>
```

Source of these prompt duplication for me comes from trying to figure arglist of a symbol at point. It uses comint redirect feature. At this point I have only the speculation, but since comint redirect is looking for prompt as the end of output it sometimes would receive `2\nuser=>` while in redirect mode leaving second `user=>` to be passed to regular process filter thus ending in comint buffer. This makes sense to me after reading how `comint-redirect-completed` and `accept-process-output` work.

**Pull request closed without merging**
